let Influx = require('influx');
let bluebird = require('bluebird');
let Health = require('../app/models/Health');
let influx = new Influx.InfluxDB({
    host: '10.104.240.107',
    port: 8086,
    database: 'varnish'
});

module.exports = {
    /*
         Will be translated to get("/api/health") (first level is generated by controller name)
     */
    get_index(req, res) {

        res.send('Hello');
    },

    get_status(req, res) {
        let reqPromiseArray = [];

        reqPromiseArray.push(influx.queryRaw('select * from cpu limit 1'));
        reqPromiseArray.push(influx.queryRaw('select * from diskio limit 4'));
        reqPromiseArray.push(influx.queryRaw('select * from disk limit 4'));
        reqPromiseArray.push(influx.queryRaw('select * from mem limit 1'));
        reqPromiseArray.push(influx.queryRaw('select * from sysstat_network limit 4'));
        reqPromiseArray.push(influx.queryRaw('select * from cpu limit 1'));   //ยังไม่ถูกต้อง

        bluebird.all(reqPromiseArray).then(function (reqResultArray) {
            let data = [];
            reqResultArray.forEach(function (result) {
                data.push(result.results);
            });

            let health = new Health(data);
            res.json(health.getResult());
        });

    }
}