module.exports = {
    /*
         Will be translated to get("/api/health") (first level is generated by controller name)
     */
    get_index: function (req, res) {
        
        var reqPromiseArray = [];

        reqPromiseArray.push(influx.queryRaw('select * from cpu limit 1'));
        reqPromiseArray.push(influx.queryRaw('select * from diskio limit 4'));
        reqPromiseArray.push(influx.queryRaw('select * from disk limit 4'));
        reqPromiseArray.push(influx.queryRaw('select * from mem limit 1'));
        reqPromiseArray.push(influx.queryRaw('select * from sysstat_network limit 4'));
        reqPromiseArray.push(influx.queryRaw('select * from cpu limit 1'));   //ยังไม่ถูกต้อง

        bluebird.all(reqPromiseArray).then(function (reqResultArray) {
            var all = [];
            reqResultArray.forEach(function (result) {
                all.push(result.results);
            });

            var result = new Health();
            var output = result.query(all);
            res.json(output);

        });
    }
}